#!/usr/bin/perl

# Copyright (C) 2008 Eric L. Wilhelm

use warnings;
use strict;

=head1 NAME

pmversion - print perl module version number

=cut

package bin::pmversion;

use version (); # to make vstrings print nicely

sub main {
  my (@args) = @_;

  my $mod = shift(@args);
  eval("require $mod");
  $@ and die "cannot find $mod -- $@";
  print $mod->VERSION, "\n";
}

package main;

if($0 eq __FILE__) {
  bin::pmversion::main(@ARGV);
}

# vi:ts=2:sw=2:et:sta
my $package = 'bin::pmversion';
